/*
 * Array of all event types found for:
 * Document, Element, HTMLElement, HTMLFormElement, HTMLInputElement & Window
 * at:
 * https://developer.mozilla.org/en-US/docs/Web/Events
 */

/*
    TODO: filter out the deprecated and those that can't be lead or trailed
*/
const eventTypes = [
    'afterprint',
    'afterscriptexecute',
    'animationcancel',
    'animationend',
    'animationiteration',
    'animationstart',
    'appinstalled',
    'auxclick',
    'beforeinput',
    'beforeprint',
    'beforescriptexecute',
    'beforeunload',
    'blur',
    'change',
    'click',
    'compositionend',
    'compositionstart',
    'compositionupdate',
    'contextmenu',
    'copy',
    'cut',
    'dblclick',
    'devicemotion',
    'deviceorientation',
//deprecated    'DOMActivate',
    'DOMContentLoaded',
//deprecated    'DOMMouseScroll',
    'drag',
    'dragend',
    'dragenter',
    'dragleave',
    'dragover',
    'dragstart',
    'drop',
    'error',
    'focus',
    'focusin',
    'focusout',
    'formdata',
    'fullscreenchange',
    'fullscreenerror',
    'gamepadconnected',
    'gamepaddisconnected',
    'gesturechange',
    'gestureend',
    'gesturestart',
    'gotpointercapture',
    'hashchange',
    'input',
    'invalid',
    'keydown',
//deprecated    'keypress',
    'keyup',
    'languagechange',
    'load',
    'lostpointercapture',
    'message',
    'messageerror',
//lognoise    'mousedown',
//lognoise    'mouseenter',
//lognoise    'mouseleave',
//lognoise    'mousemove',
//lognoise    'mouseout',
//lognoise    'mouseover',
//lognoise    'mouseup',
//deprecated    'mousewheel',
    'msContentZoom',
    'MSGestureChange',
    'MSGestureEnd',
    'MSGestureHold',
    'MSGestureStart',
    'MSGestureTap',
    'MSInertiaStart',
    'MSManipulationStateChanged',
    'offline',
    'online',
    'orientationchange',
    'overflow',
    'pagehide',
    'pageshow',
    'paste',
    'pointercancel',
//lognoise     'pointerdown',
//lognoise     'pointerenter',
//lognoise     'pointerleave',
    'pointerlockchange',
    'pointerlockerror',
//lognoise     'pointermove',
//lognoise     'pointerout',
//lognoise     'pointerover',
//lognoise     'pointerup',
    'popstate',
    'readystatechange',
    'rejectionhandled',
    'reset',
    'resize',
    'scroll',
    'search',
    'select',
    'selectionchange',
    'selectstart',
//deprecated    'show',
    'storage',
    'submit',
    'touchcancel',
    'touchend',
    'touchmove',
    'touchstart',
    'transitioncancel',
    'transitionend',
    'transitionrun',
    'transitionstart',
    'underflow',
    'unhandledrejection',
    'unload',
    'visibilitychange',
    'vrdisplayactivate',
    'vrdisplayblur',
    'vrdisplayconnect',
    'vrdisplaydeactivate',
    'vrdisplaydisconnect',
    'vrdisplayfocus',
    'vrdisplaypointerrestricted',
    'vrdisplaypointerunrestricted',
    'vrdisplaypresentchange',
    'webkitmouseforcechanged',
    'webkitmouseforcedown',
    'webkitmouseforceup',
    'webkitmouseforcewillbegin',
    'wheel'
]
